name: Instrumented Testing

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run_tests:

    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create keys.txt
        env:
          KEYS_TXT: ${{ secrets.KEYS_TXT }}
        run: echo $KEYS_TXT > keys.txt

      - name: Create google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $FIREBASE_SECRET > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest --stacktrace --scan

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: app/build/reports