name: Hanji Unit Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create keys.txt
        env:
          KEYS_TXT: ${{ secrets.KEYS_TXT }}
        run: echo $KEYS_TXT > keys.txt
      - name: Create google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $FIREBASE_SECRET > app/google-services.json
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace
      - name: Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}