name: Hanji Unit Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - 2.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create keys.txt
        env:
          KEYS_TXT: ${{ secrets.KEYS_TXT }}
        run: echo $KEYS_TXT > keys.txt
      - name: Create google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $FIREBASE_SECRET > app/google-services.json
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace